version: '3'

services:
  febs-admin:
    image: febs-admin:latest
    container_name: febs-admin
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--nacos.url=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8401:8401
#    restart: on-failure
  febs-gateway:
    image: febs-gateway:latest
    container_name: febs-gateway
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--febs-admin=host.docker.internal"
      - "--mongo.url=host.docker.internal"
      - "--nacos.url=host.docker.internal"
      - "--redis.url=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8301:8301
#    restart: on-failure
  febs-auth:
    image: febs-auth:latest
    container_name: febs-auth
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--febs-admin=host.docker.internal"
      - "--nacos.url=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--redis.url=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8101:8101
#    restart: on-failure
  febs-server-system:
    image: febs-server-system:latest
    container_name: febs-server-system
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--febs-admin=host.docker.internal"
      - "--febs-gateway=host.docker.internal"
      - "--nacos.url=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--febs-tx-manager=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8201:8201
    depends_on:
      - febs-tx-manager
#    restart: on-failure
  febs-server-test:
    image: febs-server-test:latest
    container_name: febs-server-test
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--nacos.url=host.docker.internal"
      - "--febs-admin=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--febs-tx-manager=host.docker.internal"
      - "--febs-gateway=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8202:8202
    depends_on:
      - febs-tx-manager
#    restart: on-failure
  febs-server-generator:
    image: febs-server-generator:latest
    container_name: febs-server-generator
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--nacos.url=host.docker.internal"
      - "--febs-admin=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--febs-gateway=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8203:8203
#    restart: on-failure
  febs-server-job:
    image: febs-server-job:latest
    container_name: febs-server-job
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--nacos.url=host.docker.internal"
      - "--febs-admin=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--febs-gateway=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8204:8204
#    restart: on-failure
  febs-tx-manager:
    image: febs-tx-manager:latest
    container_name: febs-tx-manager
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    command:
      - "--nacos.url=host.docker.internal"
      - "--febs-admin=host.docker.internal"
      - "--mysql.url=host.docker.internal"
      - "--redis.url=host.docker.internal"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 8501:8501
      - 8888:8888
#    restart: on-failure
  febs-cloud-web:
    image: febs-cloud-web
    container_name: febs-cloud-web
    volumes:
      - "/run/desktop/mnt/host/e/febs/log:/log"
    environment:
      - "TZ=Asia/Shanghai"
    ports:
      - 9527:80
#    restart: on-failure
