version: '3'

services:
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - E:\febs\mysql\data:/var/lib/mysql #挂载 MySQL数据
  redis:
    image: redis:4.0.14
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    volumes:
      - E:\febs\redis\data:/data #挂载 Redis数据
      - E:\febs\redis\conf\redis.conf:/usr/local/etc/redis/redis.conf #挂载 Redis配置
    ports:
      - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123.com
    volumes:
      - E:\febs\mongodb\data:/data/db
      - E:\febs\mongodb\logs:/data/logs
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.7.15-management
    container_name: rabbitmq
    volumes:
      - E:\febs\rabbitmq\data:/var/lib/rabbitmq #挂载 RabbitMQ数据
      - E:\febs\rabbitmq\log:/var/log/rabbitmq #挂载 RabbitMQ日志
    ports:
      - 5672:5672
      - 15672:15672